# Generated by Django 5.0.1 on 2025-11-25 11:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this content type (e.g., "blog_post", "product")', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Name must start with lowercase letter and contain only lowercase letters, numbers, and underscores', regex='^[a-z][a-z0-9_]*$')])),
                ('display_name', models.CharField(help_text='Human-readable name (e.g., "Blog Post", "Product")', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Content Type',
                'verbose_name_plural': 'Content Types',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Field name must start with lowercase letter and contain only lowercase letters, numbers, and underscores', regex='^[a-z][a-z0-9_]*$')])),
                ('display_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=500, null=True)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('choices', models.JSONField(blank=True, help_text='For select fields: ["option1", "option2", "option3"]', null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='content_types_app.contenttype')),
            ],
            options={
                'verbose_name': 'Content Type Field',
                'verbose_name_plural': 'Content Type Fields',
                'ordering': ['order', 'id'],
                'unique_together': {('content_type', 'field_name')},
            },
        ),
    ]
